[package]
name = "one-desktop"
version = "0.1.1"
description = "ONE focus timer desktop application"
authors = ["ryusuke2003"]
edition = "2021"

[lib]
name = "one_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
