from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
INSIGHTS_SOURCE = (ROOT / "src" / "features" / "progress" / "progressInsights.js").read_text(encoding="utf-8")
DETAILS_SOURCE = (ROOT / "src" / "features" / "progress" / "ProgressDetails.jsx").read_text(encoding="utf-8")


def fail(message):
    raise SystemExit(f"ERROR: {message}")


def require(condition, message):
    if not condition:
        fail(message)


def section(source, start_marker, end_marker):
    start = source.find(start_marker)
    if start < 0:
        fail(f"{start_marker} が見つかりません")
    end = source.find(end_marker, start + len(start_marker))
    if end < 0:
        fail(f"{end_marker} が見つかりません")
    return source[start:end]


def main():
    require("function currentDayAriaLabel(key, count)" in INSIGHTS_SOURCE,
            "今日の読み上げ文を共通関数へ集約してください")
    require("`今日 ${key}: ${count}回`" in INSIGHTS_SOURCE,
            "今日の読み上げには『今日』・日付・回数を含めてください")

    history = section(INSIGHTS_SOURCE, "function buildHistoryWindow(history, today)", "export function buildProgressInsights")
    require("const current = key === todayKey;" in history, "7日履歴は日付キーで今日を判定してください")
    require("current ? currentDayAriaLabel(key, count)" in history,
            "7日履歴の今日には『今日』を含む読み上げを設定してください")
    require("weekday: current ? '今日'" in history, "7日履歴の今日ラベルを維持してください")

    insights = section(INSIGHTS_SOURCE, "export function buildProgressInsights", "\n}")
    require("const current = key === todayKey;" in insights, "30日マップは日付キーで今日を判定してください")
    require("current ? currentDayAriaLabel(key, count)" in insights,
            "30日マップの今日だけ『今日』を含む読み上げにしてください")

    require("aria-current={day.current ? 'date' : undefined}" in DETAILS_SOURCE,
            "7日履歴の今日には aria-current=date を付けてください")
    require("cell.current ? 'is-today' : ''" in DETAILS_SOURCE,
            "30日マップの今日を見た目でも区別してください")
    require("aria-current={cell.current ? 'date' : undefined}" in DETAILS_SOURCE,
            "30日マップの今日には aria-current=date を付けてください")
    require("tabIndex" not in DETAILS_SOURCE and "tabindex" not in DETAILS_SOURCE.lower(),
            "履歴セルを個別のTab移動対象にしないでください")

    print("Current-date semantics are generated by the React progress read model.")


if __name__ == "__main__":
    main()
